### PR TITLE
implement floor and ceil for f64 and f32 types

### PR DESCRIPTION
**Pull request by kralverde**
This PR implements the `floor` and `ceil` functions for the f64 and f32 types.

### CODE REVIEW

**Comment by kralverde** [comment]
I added test cases, but I'm not sure how to actually test on relevant hardware... there doesn't seem to be any github hooks or anything

**Review by Lokathor — APPROVED** [review]

**Comment by CryZe** [comment]
The WASI target is now called `wasm32-wasip1`

**Comment by kralverde** [comment]
> The WASI target is now called `wasm32-wasip1`

Thanks this worked, but now it looks like there's some kind of permission issue with the workflows...

**Comment by kralverde** [comment]
Now an architecture error... I'm not super familiar with wasm if anyone wants to pitch in

**Comment by Lokathor** [comment]
I'm gonna merge this, the wasm stuff shouldn't be on your shoulders.

@CryZe can you fix the wasm ci setup at some point later?

**Comment by CryZe** [comment]
The problem is that it's still the old target name here (and possibly other places): https://github.com/Lokathor/wide/blob/main/.cargo-ci/config#L11

**Pull request merged**
