### PR TITLE
Add aarch64 support along with emulator build as action

### PR DESCRIPTION
**Pull request by mcroomp**
Added neon intrinsics support for aarch64, along with emulator for testing.

Don't support armv7 at this point since it is unstable.

### CODE REVIEW

**Comment by Lokathor** [comment]
This looks good so far, my main comment would be that newly added function/methods should generally be marked as `#[inline]` and also `#[must_use]`

**Comment by mcroomp** [comment]
> 

You mean the Default and PartialEq trait? Other than that I don't think I added any functions

**Comment by Lokathor** [comment]
Yep, even trait methods need to be specifically marked with `#[inline]` to make them eligible for inlining across codegen units when there's no generics.

**Comment by Lokathor** [comment]
Yeah that makes sense.

**Review by Lokathor — APPROVED** [review]
Looks good here. Should I merge or is there even more to do?

**Comment by mcroomp** [comment]
I think this is good to go now. I merged some conflicts with the previous change and also made it only use neon on aarch64, since armv7 also supports neon but causes compile issues since it is unstable.

**Comment by mcroomp** [comment]
Thank you! Let me know when you publish the crate... can't wait to start using the new features :)

**Comment by Lokathor** [comment]
I think we'll wait a little longer to sort out https://github.com/Lokathor/wide/pull/127 and then things should be fine to publish.

**Pull request merged**
