### PR TITLE
Adds conversion functions from integers to floats

### PR DESCRIPTION
**Pull request by Mottl**
This PR adds four conversion functions from integers to floats:
`f32x4::from_i32x4`
`f32x8::from_i32x8`
`f64x2::from_i32x4`
`f64x4::from_i32x4`

### CODE REVIEW

**Comment by Lokathor** [comment]
Looks like the build errors are because you're trying to use nightly stuff.

Also, these should either be `From` impls, or they should have more descriptive names that help the reader understand why it's not just a normal From impl. eg: `f64x2::from_i32x4_lower2(x)` lets the reader understand that they're dropping half their lanes.

**Comment by Mottl** [comment]
Thanks for comments! I chose to implement `From`.

**Comment by Mottl** [comment]
Btw, is there a reason for aarch64 in `#[cfg(all(target_feature="neon",target_arch="aarch64"))]`?
(compare with `#[cfg(target_feature="sse2")]`).

**Comment by mcroomp** [comment]
They aren't really simple From since they are potentially lossy... i32 -> f32

**Comment by Mottl** [comment]
Yes, according to `From` description you are right. Changed from `From` impls to ordinary functions.

**Comment by Mottl** [comment]
@Lokathor, does it look good now?

**Review by Lokathor — APPROVED** [review]

**Comment by Lokathor** [comment]
Released `wide-0.7.26`

Sorry about the delay! last weekend got unexpectedly busy

**Pull request merged**
