### PR TITLE
Cmp traits

### PR DESCRIPTION
**Pull request by ronniec95**
Usability improvements. Can now compare f32x4.cmp_eq(2.0). Implemented for most types.

### CODE REVIEW

**Comment by ronniec95** [comment]
Build failure on github due to " error: toolchain 'nightly-x86_64-pc-windows-msvc' is not installed"? Is that's a change on your side?

**Comment by Lokathor** [comment]
Nope, sometimes the CI just dies from bad network during the rustup download. Let me restart it.

**Comment by Lokathor** [comment]
Hmm. Rustup failed again. I'll try this later today, but I'm still pretty sure that it's just a temporary network hiccup.

**Comment by Lokathor** [comment]
@ronniec95: CI works again, you're back to just plain test failures.

**Comment by ronniec95** [comment]
Looks good. Happy to merge this

**Pull request merged**
