### PR TITLE
Added exp() function to f32x4 and f64x2 inspired/copied from Agner Fo…

### PR DESCRIPTION
**Pull request by ronniec95**
…g vcl library with corresponding tests. Ready for review.

### CODE REVIEW

**Comment by Lokathor** [comment]
This is good. I might poke a few spots around just for style, but i can do that myself later. Should I merge it now?

**Comment by ronniec95** [comment]
Go for it. I'm use **rustfmt** for styling incidentally - do you use something else?

**Comment by Lokathor** [comment]
oh the rustfmt is fine, but I'll probably move the polynomial functions up to lib.rs now that there's some crossover between f32x4 and f64x2.

**Comment by Lokathor** [comment]
Also, I can't publish a crate update until later today (~6 hrs) so if you want to get the ln/log stuff into the same update there's time available.

**Comment by ronniec95** [comment]
I've done the log functions but it's not yet tested. It's late here too so I'll have to pick it up tomorrow if that's OK. At 0.5.2 release for the ln functions is fine :)

**Comment by Lokathor** [comment]
okay, no rush then

**Pull request merged**
