### PR TITLE
Add powf

### PR DESCRIPTION
**Pull request by ronniec95**
Added powf() functions for all the f32/f64 types.
Also fixed ln() for i586
Disabled some tests in 0.5.2 for asin_acos which aren't working yet on i586

### CODE REVIEW

**Comment by ronniec95** [comment]
Hi Lokathor

If you are happy with this please feel free to merge.

I've ensured the merge works with 0.5.2 but as noted some of the **f32x4/f32x8 asin_acos** tests don't work for i586 so I've had to disabled those tests until  termhn addresses those.

I think now we have a first complete SIMD library with the crucial math functions that make it usable for real work.

**Comment by ronniec95** [comment]
Do not merge!

**Comment by Lokathor** [comment]
okay, will not merge it

**Comment by ronniec95** [comment]
Now you can merge.

Please check the notes. There is a bug but it should only affect nan handling in some cases. If you can take a look and fix it, it would be appreciated. (f64x4,f64x2 sign_bits)

**Comment by Lokathor** [comment]
i can look at and probably merge this later today.

I'm not sure I'll have time for `wide` bug fixing today or this weekend.

However, T-libs is starting a project group for portable simd in `core` very soon, so with luck a lot of code either here or in  `packed_simd` will slot right in. The timeline goal is to have it done and stable by late 2021

https://github.com/rust-lang/rfcs/pull/2977

**Comment by ronniec95** [comment]
`packed_simd` is the more powerful library with it's comprehensive set of math functions and everything, and I would use it except that it doesn't work on stable. But yes, keep in the loop, I'd love to contribute

**Comment by Lokathor** [comment]
oops, looks like the other PR made a few conflicts here.

**Comment by ronniec95** [comment]
Ok will look and fix tomorrow.

**Comment by ronniec95** [comment]
Conflicts resolved. Looks better. Feel free to merge.
When's the next release? I want to push some of my own code up with depends on these new functions

**Comment by Lokathor** [comment]
Have there been breaking changes yet? i think we can keep publishing under the 0.5 series at the moment

**Comment by ronniec95** [comment]
Great - will wait for your next 0.5.4 release.

Also had a look at packed_simd, it uses Sleef to implement the math functions; for a core library it would be strange to then depend on a C++ library. A pure rust implementation which you now have would be much better

**Comment by Lokathor** [comment]
okay, just put it out as 0.5.3

**Pull request merged**
